title: Md Maksud Hossain
Address: 201 North Ibrahimpur, Dhaka - 1206
Contact: 01756610535

# description: Software Engineer, QA @ Grameenphone.
baseurl: "/maksud_pranto/"
url: ""
photo_url: "my-photo.jpg"

# This is an optional section
# You can skip filling in one or more of the items in this section
email: "maksudpranto@gmail.com"
linkedin: "http://linkedin.com/in/mhpranto"
github: "https://github.com/maksudpranto"


markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  
